ticket_server_addr = "127.0.0.1:8080"
ticket_server_tls.key = "/tls/tls.key"
ticket_server_tls.cert = "/tls/tls.crt"
data_server_enabled = true
data_server_addr = "127.0.0.1:8081"
data_server_cors_allow_origins = "All"
data_server_local_path = "/data"
data_server_tls.cert = "/tlsDataServer/tls.crt"
data_server_tls.key = "/tlsDataServer/tls.key"

[[resolvers]]
regex = ".*"
substitution_string = "$0"

# If dataServer.ingress.enabled is set to true, a way to return the correct url to the client
# is to use the configuration below.
[resolvers.storage]
# The url that will be used for the client's url
response_url = "http://data-server.local/"
# # if set to true, the client will not check the certificate validity
danger_accept_invalid_certs = true

[resolvers.storage.endpoints]
index = "http://127.0.0.1:8081/"
file = "http://127.0.0.1:8081/"