{{- if or .Values.tls.clusterIssuer .Values.tls.issuer }}
{{- if and .Values.tls.clusterIssuer .Values.tls.issuer }}
          {{- fail "Only one of tls.issuer or tls.clusterIssuer should be set" }}
{{- end -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "htsget-rs.fullname" . }}-certs
spec:
  # Secret names are always required.
  secretName: {{ template "htsget-rs.fullname" . }}-certs

  duration: 2160h # 90d

  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: {{ template "htsget-rs.fullname" . }}
  isCA: false
  privateKey:
    algorithm: Ed25519
  usages:
    - server auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - {{ template "htsget-rs.fullname" . }}
    - {{ template "htsget-rs.fullname" . }}.{{ .Release.Namespace }}.svc
  ipAddresses:
    - 127.0.0.1
  # Issuer references are always required.
  issuerRef:
    name:
      {{ ternary (printf "%s" .Values.tls.issuer) (printf "%s" .Values.tls.clusterIssuer) (empty .Values.tls.clusterIssuer )}}
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: {{ ternary "Issuer" "ClusterIssuer" (empty .Values.tls.clusterIssuer )}}
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
{{- end -}}
