apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "htsget-rs.fullname" . }}-config
data:
  download-config.toml: |-
    ticket_server_addr = "0.0.0.0:8080"
    ticket_server_cors_allow_origins = "All"

    [[resolvers]]
    regex = "(.*)"
    substitution_string = "$1"

    [resolvers.object_type]
    # if set to true, response_url must point to /s3-encrypted endpoint
    send_encrypted_to_client = false
    #private_key = "/config/server-rs.sec.pem"
    #public_key = "/config/server-rs.pub.pem"

    [resolvers.storage]
    # The url that will be used for the client's url
    # response_url = "http://host.minikube.internal:8443/s3-enrcypted/"
    response_url = "http://host.minikube.internal:8443/s3/"
    forward_headers = true

    [resolvers.storage.endpoints]
    index = "http://host.minikube.internal:8443/s3/"
    # Header and file url
    file = "http://host.minikube.internal:8443/s3-encrypted/"
    # file = "http://host.minikube.internal:8443/s3/"
