apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "htsget-rs.fullname" . }}-config
data:
  download-config.toml: |-
{{- if .Values.configMapData }}
{{- .Values.configMapData | nindent 4 }}
{{- else }}
    ticket_server_addr = "127.0.0.1:8080"
    ticket_server_cors_allow_origins = "All"

    [[resolvers]]
    regex = "(.*)"
    substitution_string = "$1"

    [resolvers.object_type]
    send_encrypted_to_client = {{ .Values.htsget.sendEncryptedToClient }}

    [resolvers.storage]
    response_url = {{ .Values.htsget.responseUrl | quote }}
    forward_headers = {{ .Values.htsget.forwardHeaders }}

    [resolvers.storage.endpoints]
    index = {{ .Values.htsget.index | quote }}
    file = {{ .Values.htsget.file | quote }}

{{- end }}
