apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "htsget-rs.fullname" . }}
  labels:
    role: htsget
    app: {{ template "htsget-rs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ template "htsget-rs.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "htsget-rs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        role: htsget
        {{- include "htsget-rs.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "htsget-rs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["htsget-actix"]
          args: ["--config", "/config/download-config.toml"]
          env:
          - name: FORMATTING_STYLE
            value: {{ default "Full" .Values.htsget.formattingStyle }}
          - name: RUST_LOG
            value: {{ default "info" .Values.htsget.rustLog }}
          ports:
            - name: htsget
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /reads/service-info
              port: htsget
              scheme: {{ ternary "HTTPS" "HTTP" ( .Values.tls.enabled) }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /reads/service-info
              port: htsget
              scheme: {{ ternary "HTTPS" "HTTP" ( .Values.tls.enabled) }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- if and .Values.htsget.c4gh.privateKey .Values.htsget.c4gh.publicKey }}
            - name: c4gh
              mountPath: /{{ required "A path for the c4gh keys is required" .Values.htsget.c4ghPath }}
            {{- end }}
            {{- if .Values.tls.enabled}}
            - name: tls
              mountPath: /{{ required "A path for tls certificates is required" .Values.htsget.tlsPath }}
            {{- end }}
            {{- if and .Values.htsget.tls.urlStorage.cert .Values.htsget.tls.urlStorage.key }}
            - name: client-certs
              mountPath: /config/client-{{ required "A path for tls certificates is required" .Values.htsget.tlsPath }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "htsget-rs.fullname" . }}-config
      {{- if and .Values.htsget.c4gh.privateKey .Values.htsget.c4gh.publicKey }}
        - name: c4gh
          secret:
            defaultMode: 0440
            secretName: {{ required "A secret for the c4gh key is required" .Values.c4gh.secretName }}
            items:
            - key: {{ .Values.htsget.c4gh.privateKey | quote }}
              path: {{ .Values.htsget.c4gh.privateKey | quote }}
            - key: {{ .Values.htsget.c4gh.publicKey | quote }}
              path: {{ .Values.htsget.c4gh.publicKey | quote }}
      {{- end }}
      {{- if .Values.tls.enabled }}
        - name: tls
        {{- if or .Values.tls.clusterIssuer .Values.tls.issuer }}
          secret:
            defaultMode: 0440
            secretName: {{ template "htsget-rs.fullname" . }}-certs
        {{- else }}
          secret:
            defaultMode: 0440
            secretName: {{ required "A certificate issuer or a TLS secret name is required" .Values.tls.secretName }}
        {{- end }}
      {{- end }}
      {{- if and .Values.htsget.tls.urlStorage.cert .Values.htsget.tls.urlStorage.key }}
        - name: client-certs
        {{- if or .Values.tls.clusterIssuer .Values.tls.issuer }}
          secret:
            defaultMode: 0440
            secretName: {{ template "htsget-rs.fullname" . }}-certs
        {{- else }}
          secret:
            defaultMode: 0440
            secretName: {{ required "A certificate issuer or a TLS secret name is required for the client" .Values.htsget.tls.urlStorage.secretName }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
