apiVersion: v1
kind: Service
metadata:
  name: {{ include "htsget-rs.fullname" . }}
  labels:
    {{- include "htsget-rs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: htsget
      protocol: TCP
      name: htsget
  selector:
    {{- include "htsget-rs.selectorLabels" . | nindent 4 }}
---
{{- if .Values.htsget.dataServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "htsget-rs.fullname" . }}-data-server
  labels:
    {{- include "htsget-rs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dataServer.service.type }}
  ports:
    - port: {{ .Values.dataServer.service.port }}
      targetPort: data-server
      protocol: TCP
      name: data-server
  selector:
    {{- include "htsget-rs.selectorLabels" . | nindent 4 }}
{{- end -}}