apiVersion: v2
name: htsget-rs
description: A Helm chart for Kubernetes

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# This is the chart version.
version: 0.1.0

# corresponds to the default image tag
appVersion: "20240415"
